apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-resolver-ds-sa
  namespace: kube-system
#automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-resolver-ds-sa-clusteradmin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: node-resolver-ds-sa